image: alpine:edge

stages:
  - qa
  - test
  - deploy

lint:
  stage: qa
  before_script:
    - apk add --no-cache vala-lint
  script:
    - io.elementary.vala-lint

test:
  stage: test
  before_script:
    - apk add --no-cache vala gtk+3.0-dev libgee-dev sqlite-dev libhandy1-dev meson build-base git gobject-introspection-dev libsoup-dev rest-dev json-glib-dev libsecret-dev
  script:
    - meson build
    - meson test -v -C build

non-null:
  stage: test
  before_script:
    - apk add --no-cache vala gtk+3.0-dev libgee-dev sqlite-dev libhandy1-dev meson build-base git gobject-introspection-dev libsoup-dev rest-dev json-glib-dev libsecret-dev
  script:
    - env VALAC_FLAGS="--enable-experimental-non-null" meson build
    - meson test -v -C build

pages:
  stage: deploy
  before_script:
    - apk add --no-cache vala gtk+3.0-dev libgee-dev sqlite-dev libhandy1-dev meson alpine-sdk git
  script:
    - meson -Ddocs=true build
    - meson compile -C build
    - rm -rf public
    - mv build/docs/ public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
