[package]
name = "health"
version = "0.92.6"
edition = "2018"
license = "GPL-3.0-or-later"

[lib]
name = "libhealth"
path = "src/lib.rs"

[[bin]]
name = "health"
path = "src/main.rs"

[dependencies.adw]
git = "https://gitlab.gnome.org/bilelmoussaoui/libadwaita-rs"
package = "libadwaita"

[dependencies.bitflags]
version = "1.0"

[dependencies.chrono]
version = "0.4"

[dependencies.csv]
version = "1.1"

[dependencies.easy-ext]
version = "0.2"

[dependencies.failure]
version = "0.1"

[dependencies.gettext-rs]
version = "0.6"
features = ["gettext-system"]

[dependencies.gdk]
git = "https://github.com/gtk-rs/gtk4-rs"
package = "gdk4"

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk4-rs"
package = "gtk4"

[dependencies.gtk-macros]
version = "0.2.0"

[dependencies.gio]
git = "https://github.com/gtk-rs/gtk-rs"
features = ["v2_60"]

[dependencies.glib]
git = "https://github.com/gtk-rs/gtk-rs"
features = ["v2_60"]

[dependencies.http]
version = "0.1"

[dependencies.num-derive]
version = "0.3"

[dependencies.num-traits]
version = "0.2"

[dependencies.oauth2]
version = "3"
default-features = false

[dependencies.once_cell]
version = "1.5"

[dependencies.pango]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.pangocairo]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.paste]
version = "1.0"

[dependencies.regex]
version = "1.4.3"

[dependencies.serde]
version = "1"
features = ["serde_derive"]

[dependencies.serde_json]
version = "1"

[dependencies.strum]
version = "0.20"
features = ["derive"]

[dependencies.tracker]
git = "https://gitlab.com/dleggo/tracker-rs"
package = "tracker-rs"

[dependencies.thiserror]
version = "1"

[dependencies.uom]
default-features = false
version = "0.31"
features = ["f32", "si"]

[dependencies.ureq]
version = "2"
features = ["json"]

[dependencies.secret-service]
version = "2"

[dev-dependencies.serde_test]
version = "1"

[dev-dependencies.tempfile]
version = "3"

[profile.release]
lto = true
panic = "abort"
debug = true

[profile.dev]
debug = true
